// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCotCvnhz-9oHsg1qBZJDpeGlbJigXkd8g',
    appId: '1:471974390437:web:f28e1893a293bc6521fb4c',
    messagingSenderId: '471974390437',
    projectId: 'mindinsight-a8414',
    authDomain: 'mindinsight-a8414.firebaseapp.com',
    storageBucket: 'mindinsight-a8414.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7fr8Uc25X3bAKnaIGWmwPXZZ8NCFZBq8',
    appId: '1:471974390437:android:e3a44a1e206db1a121fb4c',
    messagingSenderId: '471974390437',
    projectId: 'mindinsight-a8414',
    storageBucket: 'mindinsight-a8414.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3pVx22HBFfFQ9HjcquFNFNIQM5nGEF0k',
    appId: '1:471974390437:ios:a62f82feeff5abd121fb4c',
    messagingSenderId: '471974390437',
    projectId: 'mindinsight-a8414',
    storageBucket: 'mindinsight-a8414.firebasestorage.app',
    iosBundleId: 'com.example.fixedApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3pVx22HBFfFQ9HjcquFNFNIQM5nGEF0k',
    appId: '1:471974390437:ios:a62f82feeff5abd121fb4c',
    messagingSenderId: '471974390437',
    projectId: 'mindinsight-a8414',
    storageBucket: 'mindinsight-a8414.firebasestorage.app',
    iosBundleId: 'com.example.fixedApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCotCvnhz-9oHsg1qBZJDpeGlbJigXkd8g',
    appId: '1:471974390437:web:12a7622130e5a17221fb4c',
    messagingSenderId: '471974390437',
    projectId: 'mindinsight-a8414',
    authDomain: 'mindinsight-a8414.firebaseapp.com',
    storageBucket: 'mindinsight-a8414.firebasestorage.app',
  );

}